In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
data = pd.read_csv('./accepted_2007_to_2018Q4.csv')
data.head(5)

C:\Users\user\AppData\Local\Temp\ipykernel_6324\62786924.py:1: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('./accepted_2007_to_2018Q4.csv')

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.00,0.00,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.00,0.00,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.00,0.00,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,NaN,NaN,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.010000,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.90,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.00,0.00,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
columns_to_keep = ['loan_amnt','int_rate','installment','emp_title','emp_length','home_ownership','annual_inc','issue_d','loan_status','purpose','dti','earliest_cr_line','open_acc','pub_rec','revol_bal','revol_util','total_acc','mort_acc','pub_rec_bankruptcies','zip_code','addr_state', 'grade' , 'collections_12_mths_ex_med']

# 컬럼 제외하고 나머지 삭제
data.drop(columns=[col for col in data.columns if col not in columns_to_keep], inplace=True)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   loan_amnt                   float64
 1   int_rate                    float64
 2   installment                 float64
 3   grade                       object
 4   emp_title                   object
 5   emp_length                  object
 6   home_ownership              object
 7   annual_inc                  float64
 8   issue_d                     object
 9   loan_status                 object
 10  purpose                     object
 11  zip_code                    object
 12  addr_state                  object
 13  dti                         float64
 14  earliest_cr_line            object
 15  open_acc                    float64
 16  pub_rec                     float64
 17  revol_bal                   float64
 18  revol_util                  float64
 19  total_acc                   float64
 20  collections_12_mths_ex_med  float64
 21  mort_acc                    float64
 22  pub_rec_bankruptcies        float64
dtypes: float64(13), object(10)
memory usage: 396.7+ MB

In [6]:
pd.options.display.float_format = '{:.5f}'.format

In [7]:
target = data['loan_status']

In [8]:
data['earliest_cr_line'].fillna(0)

0          Aug-2003
1          Dec-1999
2          Aug-2000
3          Sep-2008
4          Jun-1998
             ...
2260696    Feb-1995
2260697    Jul-1999
2260698    Jun-1996
2260699           0
2260700           0
Name: earliest_cr_line, Length: 2260701, dtype: object

In [9]:
emp_title_other = data['emp_title']
emp_title_other = emp_title_other.to_frame()
emp_title_other_ = emp_title_other.applymap(lambda x: 1 if pd.notnull(x) else x)
emp_title_other_.fillna(0 , inplace= True)
data['emp'] = emp_title_other_

In [10]:
data = data.drop('emp_title',  axis = 1)

In [11]:
data['loan_status'].value_counts()

Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: loan_status, dtype: int64

## feature 삭제

In [12]:
data.drop('pub_rec_bankruptcies' , axis = 1 , inplace=True)
data.head(5)

,loan_amnt,int_rate,installment,grade,emp_length,home_ownership,annual_inc,issue_d,loan_status,purpose,zip_code,addr_state,dti,earliest_cr_line,open_acc,pub_rec,revol_bal,revol_util,total_acc,collections_12_mths_ex_med,mort_acc,emp
0,3600.00000,13.99000,123.03000,C,10+ years,MORTGAGE,55000.00000,Dec-2015,Fully Paid,debt_consolidation,190xx,PA,5.91000,Aug-2003,7.00000,0.00000,2765.00000,29.70000,13.00000,0.00000,1.00000,1.00000
1,24700.00000,11.99000,820.28000,C,10+ years,MORTGAGE,65000.00000,Dec-2015,Fully Paid,small_business,577xx,SD,16.06000,Dec-1999,22.00000,0.00000,21470.00000,19.20000,38.00000,0.00000,4.00000,1.00000
2,20000.00000,10.78000,432.66000,B,10+ years,MORTGAGE,63000.00000,Dec-2015,Fully Paid,home_improvement,605xx,IL,10.78000,Aug-2000,6.00000,0.00000,7869.00000,56.20000,18.00000,0.00000,5.00000,1.00000
3,35000.00000,14.85000,829.90000,C,10+ years,MORTGAGE,110000.00000,Dec-2015,Current,debt_consolidation,076xx,NJ,17.06000,Sep-2008,13.00000,0.00000,7802.00000,11.60000,17.00000,0.00000,1.00000,1.00000
4,10400.00000,22.45000,289.91000,F,3 years,MORTGAGE,104433.00000,Dec-2015,Fully Paid,major_purchase,174xx,PA,25.37000,Jun-1998,12.00000,0.00000,21929.00000,64.50000,35.00000,0.00000,6.00000,1.00000

In [13]:
data.drop(['addr_state'], axis = 1, inplace=True)

In [14]:
data.drop(['zip_code'],axis = 1 , inplace = True)

In [15]:
data = data[data['annual_inc'] <= 250000]
data = data[data['dti'] <= 50]
data = data[data['open_acc'] <= 40]
data = data[data['total_acc'] <= 80]
data = data[data['revol_util'] <= 120]
data = data[data['revol_bal'] <= 250000]

In [16]:
data = data.dropna()

## 전처리


명목형 : home_ownership , loan_status , purpose , 

순서형 : emp_length , collections_12_mths_ex_med , earliest_cr_line , issue_d


------

EDA 이후 삭제한 피처들

addr_state , pub_rec_bankruptcies

------

earliest_cr_line , issue_d 의 경우 , 현재 날짜 - 기존 날짜로 총합 계산 -> ordinalEncoding -> minmaxScaling




<계획>
날짜 피처 : earliest_cr_line , issue_d  -> ohe
명목형 : ohe
순서형 : ord

------
<br>
순서형 : ord_num
<br>
명목형 : ohe_num
<br>

------

y값(target) : 순서형 


------
이진 분류로 변경 (해도 될까 ? ): annual_inc,  pub_rec , revol_bal

In [17]:
data['earliest_cr_line'] = pd.to_datetime(data['earliest_cr_line'], format = '%b-%Y')
data['issue_d'] = pd.to_datetime(data['issue_d'],format = '%b-%Y')

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2022619 entries, 0 to 2260698
Data columns (total 20 columns):
 #   Column                      Dtype
---  ------                      -----
 0   loan_amnt                   float64
 1   int_rate                    float64
 2   installment                 float64
 3   grade                       object
 4   emp_length                  object
 5   home_ownership              object
 6   annual_inc                  float64
 7   issue_d                     datetime64[ns]
 8   loan_status                 object
 9   purpose                     object
 10  dti                         float64
 11  earliest_cr_line            datetime64[ns]
 12  open_acc                    float64
 13  pub_rec                     float64
 14  revol_bal                   float64
 15  revol_util                  float64
 16  total_acc                   float64
 17  collections_12_mths_ex_med  float64
 18  mort_acc                    float64
 19  emp                         float64
dtypes: datetime64[ns](2), float64(13), object(5)
memory usage: 324.1+ MB

In [19]:
import pandas as pd
from datetime import datetime

data['cr_line_period'] = (datetime.now() - data['earliest_cr_line']).dt.days
data['issue_d_period'] = (datetime.now() - data['issue_d']).dt.days

In [20]:
data.drop('earliest_cr_line' , axis = 1 , inplace= True)
data.drop('issue_d' , axis= 1 , inplace= True)

In [21]:
from sklearn.preprocessing import OrdinalEncoder

ord = OrdinalEncoder()

ord_feature = ['cr_line_period' , 'issue_d_period']

data[ord_feature]= ord.fit_transform(data[ord_feature])

In [22]:
data = data[data['collections_12_mths_ex_med'] < 7]

In [23]:
data['collections_12_mths_ex_med'].value_counts()

0.00000    1987971
1.00000      32116
2.00000       2126
3.00000        247
4.00000         85
5.00000         35
6.00000         15
Name: collections_12_mths_ex_med, dtype: int64

In [24]:
emp_length_1 = {'< 1 year': 1 , '1 year': 2 , '2 years' : 3 , '3 years': 4 , '4 years' : 5 , '5 years' : 6 , '6 years' : 7 , '7 years': 8 , '8 years':9 ,'9 years': 10 , '10+ years':11}

data['emp_length'] = data['emp_length'].map(emp_length_1)

In [25]:
data['grade'].value_counts()

B    594131
C    586519
A    383305
D    289509
E    121096
F     37318
G     10717
Name: grade, dtype: int64

In [26]:
grade_1 = {'A' : 0 ,'B' : 1, 'C' : 2, 'D' : 3, 'E' : 4, 'F' : 5, 'G' : 6}

data['grade'] = data['grade'].map(grade_1)

In [27]:
data['grade'].value_counts()

1    594131
2    586519
0    383305
3    289509
4    121096
5     37318
6     10717
Name: grade, dtype: int64

In [28]:
from sklearn.preprocessing import MinMaxScaler

Mm_feature = ['emp_length', 'grade', 'collections_12_mths_ex_med' , 'cr_line_period','issue_d_period']

Mm = MinMaxScaler()

data[Mm_feature] = Mm.fit_transform(data[Mm_feature])

In [29]:
from sklearn.preprocessing import OneHotEncoder

ohe_feature = ['home_ownership'  , 'purpose']

ohe = OneHotEncoder()

ohe_num = ohe.fit_transform(data[ohe_feature])

In [30]:
data.drop(ohe_feature, axis = 1 , inplace = True)

In [31]:
from sklearn.preprocessing import StandardScaler

num_features = ['loan_amnt','int_rate','installment','annual_inc','dti','open_acc','pub_rec','revol_bal','revol_util','total_acc','mort_acc']

std_saller = StandardScaler()

data[num_features] = std_saller.fit_transform(data[num_features])

In [32]:
data.head(5)

,loan_amnt,int_rate,installment,grade,emp_length,annual_inc,loan_status,dti,open_acc,pub_rec,revol_bal,revol_util,total_acc,collections_12_mths_ex_med,mort_acc,emp,cr_line_period,issue_d_period
0,-1.26790,0.18096,-1.23009,0.33333,1.00000,-0.53053,Fully Paid,-1.45485,-0.84841,-0.34325,-0.76112,-0.85273,-0.94952,0.00000,-0.28143,1.00000,0.20082,0.44444
1,1.04748,-0.23228,1.40553,0.33333,1.00000,-0.27806,Fully Paid,-0.27759,1.87361,-0.34325,0.30809,-1.28117,1.18197,0.00000,1.31731,1.00000,0.26093,0.44444
2,0.53173,-0.48230,-0.05968,0.16667,1.00000,-0.32855,Fully Paid,-0.88999,-1.02988,-0.34325,-0.46936,0.22858,-0.52322,0.00000,1.85022,1.00000,0.25000,0.44444
3,2.17773,0.35866,1.44189,0.33333,1.00000,0.85803,Current,-0.16160,0.24040,-0.34325,-0.47319,-1.59128,-0.60848,0.00000,-0.28143,1.00000,0.11749,0.44444
4,-0.52171,1.92901,-0.59928,0.83333,0.30000,0.71749,Fully Paid,0.80225,0.05893,-0.34325,0.33432,0.56725,0.92619,0.00000,2.38314,1.00000,0.28552,0.44444

## y값 변환

In [33]:
data['loan_status'].value_counts()

Fully Paid            964317
Current               789948
Charged Off           237805
Late (31-120 days)     19082
In Grace Period         7607
Late (16-30 days)       3803
Default                   33
Name: loan_status, dtype: int64

In [ ]:
target_1 = {'Fully Paid':0 , 'Current':1 , 'Charged Off':2, 'Late (31-120 days)' : 3 , 'In Grace Period': 4, 'Late (16-30 days)':5, 'Default':6 }
data['loan_status']= data['loan_status'].map(target_1)

In [35]:
data['loan_status'].value_counts(dropna = False)

0    964317
1    789948
2    237838
3     30492
Name: loan_status, dtype: int64

## 모든 데이터 합치기

In [36]:
from scipy import sparse

data_sparse = sparse.hstack([sparse.csr_matrix(data),
                               ohe_num
                               ],
                               
                               format = 'csr')

In [37]:
#data.to_csv('./train.csv', index = False)

In [38]:
y = data['loan_status']

In [39]:
data = data.drop('loan_status' , axis = 1)

In [40]:
num_train = len(data)

X_train = data_sparse[:num_train]
X_test = data_sparse[num_train :]

In [41]:
from sklearn.model_selection import train_test_split

X_train , X_valid, y_train, y_valid = train_test_split(X_train, y, 
                                                       test_size=0.2, 
                                                       random_state=42 , 
                                                       stratify = y)

## 모델 훈련

In [42]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline 


pipeline = make_pipeline(
    SimpleImputer(strategy='most_frequent'),
    LogisticRegression(max_iter=1000, random_state=42)    
)

pipeline.fit(X_train, y_train)

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                ('logisticregression',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [43]:
# from sklearn.metrics import roc_auc_score


y_valid_preds = pipeline.predict(X_valid)

# 'multi_class' 매개변수를 'ovo' 또는 'ovr'로 설정
#roc_auc = roc_auc_score(y_valid, y_valid_preds, multi_class='ovr')

#print(f"검증 데이터 ROC AUC : {roc_auc :.4f}" )

In [44]:
from sklearn.metrics import classification_report

print(classification_report(y_valid , y_valid_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    192863
           1       1.00      1.00      1.00    157990
           2       1.00      1.00      1.00     47568
           3       1.00      1.00      1.00      6098

    accuracy                           1.00    404519
   macro avg       1.00      1.00      1.00    404519
weighted avg       1.00      1.00      1.00    404519

In [45]:
y.value_counts(sort= False)

0    964317
1    789948
2    237838
3     30492
Name: loan_status, dtype: int64

In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

rfc = RandomForestClassifier(n_estimators= 100, max_depth= 5, random_state = 0)
rfc.fit(X_train , y_train)

predict1 = rfc.predict(X_valid)
print(classification_report(y_valid , predict1))

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    192863
           1       0.89      1.00      0.94    157990
           2       0.97      0.71      0.82     47568
           3       0.00      0.00      0.00      6098

    accuracy                           0.95    404519
   macro avg       0.72      0.68      0.69    404519
weighted avg       0.94      0.95      0.94    404519

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

train만 oversampling 실행

In [47]:
y_train.value_counts()

0    771454
1    631958
2    190270
3     24394
Name: loan_status, dtype: int64

In [48]:
from imblearn.under_sampling import OneSidedSelection as OSS 
OSS_X_train , OSS_y_train = OSS(random_state = 42).fit_resample(X_train , y_train)
OSS_y_train.value_counts()

0    636751
1    615726
2    188834
3     24394
Name: loan_status, dtype: int64

In [56]:
import scipy as sp

In [64]:
oss_4C_train = sp.hstack((OSS_X_train, OSS_y_train))

C:\Users\user\AppData\Local\Temp\ipykernel_6324\3862155923.py:1: DeprecationWarning: scipy.hstack is deprecated and will be removed in SciPy 2.0.0, use numpy.hstack instead
  oss_4C_train = sp.hstack((OSS_X_train, OSS_y_train))

In [68]:
type(oss_4C_train)

numpy.ndarray

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

rfc = RandomForestClassifier(n_estimators= 100, max_depth= 5 , random_state = 0)
rfc.fit(OSS_X_train , OSS_y_train)

predict_oss = rfc.predict(X_valid)
print(classification_report(y_valid , predict_oss))

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    192863
           1       0.89      1.00      0.94    157990
           2       0.97      0.71      0.82     47568
           3       0.00      0.00      0.00      6098

    accuracy                           0.95    404519
   macro avg       0.72      0.68      0.69    404519
weighted avg       0.94      0.95      0.94    404519

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## 데이터프레임으로 바꾸고 to_csv하면 됨
```python
oss_4C_train = pd.DataFrame(oss_4c_train, columns = ['쓴', '컬럼들', '다'])
```

In [59]:
oss_4C_train.to_csv("./oss_4C_trian.csv" , index = False)

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'

In [ ]:
# from imblearn.under_sampling import TomekLinks

'Fully Paid':0 , 
<br>
'Current':1 ,
<br>
'Charged Off':2, 'Default':2
<br>
'Late (31-120 days)' : 3 , 'In Grace Period': 3, 'Late (16-30 days)':3
<br>

모델 성능 지표에 대한 개인적인 생각
- p2p 대출자들의 신용 평가 및 대출자들의 연체율을 예측하는 경우 , recall이 높은게 유리하다.
- 실제로 연체된 대출자들을 놓치지 않는 것이 중요하기 때문이다.


- 언더 샘플링 이후에도 클래스 불균형이 해소 되지 않음. 따라서 임의로 클래스 병합 및 'Current' 클래스 제거